# Form implementation generated from reading ui file 'task4.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        self.button_go_to_first = QtWidgets.QPushButton(parent=Form)
        self.button_go_to_first.setGeometry(QtCore.QRect(10, 280, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_go_to_first.setFont(font)
        self.button_go_to_first.setObjectName("button_go_to_first")
        self.button_go_to_previous = QtWidgets.QPushButton(parent=Form)
        self.button_go_to_previous.setGeometry(QtCore.QRect(60, 280, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_go_to_previous.setFont(font)
        self.button_go_to_previous.setObjectName("button_go_to_previous")
        self.button_go_to_next = QtWidgets.QPushButton(parent=Form)
        self.button_go_to_next.setGeometry(QtCore.QRect(700, 280, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_go_to_next.setFont(font)
        self.button_go_to_next.setObjectName("button_go_to_next")
        self.button_go_to_last = QtWidgets.QPushButton(parent=Form)
        self.button_go_to_last.setGeometry(QtCore.QRect(750, 280, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.button_go_to_last.setFont(font)
        self.button_go_to_last.setObjectName("button_go_to_last")
        self.label_image = QtWidgets.QLabel(parent=Form)
        self.label_image.setGeometry(QtCore.QRect(110, 10, 580, 580))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_image.setFont(font)
        self.label_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image.setObjectName("label_image")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_go_to_first.setText(_translate("Form", "<<"))
        self.button_go_to_previous.setText(_translate("Form", "<"))
        self.button_go_to_next.setText(_translate("Form", ">"))
        self.button_go_to_last.setText(_translate("Form", ">>"))
        self.label_image.setText(_translate("Form", "label_image"))
