# Form implementation generated from reading ui file 'task6_application.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicationForm(object):
    def setupUi(self, ApplicationForm):
        ApplicationForm.setObjectName("ApplicationForm")
        ApplicationForm.resize(480, 640)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=ApplicationForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 280, 481, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_info = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_info.setContentsMargins(0, 0, 0, 0)
        self.layout_info.setObjectName("layout_info")
        self.label_info = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_info.setFont(font)
        self.label_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.layout_info.addWidget(self.label_info)
        self.label_login = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.layout_info.addWidget(self.label_login)

        self.retranslateUi(ApplicationForm)
        QtCore.QMetaObject.connectSlotsByName(ApplicationForm)

    def retranslateUi(self, ApplicationForm):
        _translate = QtCore.QCoreApplication.translate
        ApplicationForm.setWindowTitle(_translate("ApplicationForm", "Приложение"))
        self.label_info.setText(_translate("ApplicationForm", "Вы успешно авторизованы,"))
        self.label_login.setText(_translate("ApplicationForm", "пользователь"))
