# Form implementation generated from reading ui file 'task7_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 100)
        self.button_box = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.button_box.setGeometry(QtCore.QRect(20, 50, 260, 40))
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.line_edit = QtWidgets.QLineEdit(parent=Dialog)
        self.line_edit.setGeometry(QtCore.QRect(20, 20, 260, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit.setFont(font)
        self.line_edit.setMaxLength(1)
        self.line_edit.setObjectName("line_edit")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.line_edit.setPlaceholderText(_translate("Dialog", "Какую кнопку добавить?"))
